Experiment_name: test_agcn_resnet_1_10

# feeder
feeder: feeders.feeder_anonymization.Feeder
test_feeder_args:
  debug: False
  data_path: ./data/ntu/xrep_v2/val_data_joint.npy
  privacy_label_path: ./data/ntu/xrep_v2/val_label_privacy.pkl
  action_label_path: ./data/ntu/xrep_v2/val_label.pkl

# model
anonymizer_model: model.anonymization_res.Anonymizer
model_args:
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

action_model: model.agcn.Model
action_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

privacy_model: model.agcn.Model
privacy_model_args:
  num_class: 40
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


mamp_model: model_mamp.transformer.Transformer
mamp_model_args:
  dim_in: 3
  dim_feat: 256
  decoder_dim_feat: 256
  depth: 8
  decoder_depth: 3
  num_heads: 8
  mlp_ratio: 4
  num_frames: 120
  num_joints: 25
  patch_size: 1
  t_patch_size: 4
  qkv_bias: True
  qk_scale: None
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.
  norm_skes_loss: True
pretrained_mamp: pretrained/checkpoint-mamp-xrep_v3.pth


phase: 'test'
device: [0]
test_batch_size: 32
nesterov: True

test_action:
  batch_size: 64

test_privacy:
  batch_size: 64


pretrained_action: pretrained/ntu_agcn_joint_xrep_v2_test_0.pt
pretrained_privacy: pretrained/ntu_agcn_id_xrep_v2_test_0.pt
pretrained_privacy_test: pretrained/ntu_agcn_id_xrep_v2_test_0.pt


wandb: "project_name"
entity: "user"

weights:  pretrained/Skeleton_anonymization_resnet.pt