Experiment_name: Skeleton_anonymization_unet_0d3_2

# feeder
feeder: feeders.feeder_anonymization.Feeder
train_feeder_args:
  data_path: ./data/ntu/xrep_v2/train_data_joint.npy
  privacy_label_path: ./data/ntu/xrep_v2/train_label_privacy.pkl
  action_label_path: ./data/ntu/xrep_v2/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xrep_v2/val_data_joint.npy
  privacy_label_path: ./data/ntu/xrep_v2/val_label_privacy.pkl
  action_label_path: ./data/ntu/xrep_v2/val_label.pkl

# model
anonymizer_model: model.unet_model.UNet
model_args:
  n_channels: 3
  n_classes: 3
  bilinear: False

action_model: model.shift_gcn.Model
action_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

privacy_model: model.shift_gcn.Model
privacy_model_args:
  num_class: 40
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01


step: [60, 80, 100]

# training
device: [0]
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 140
nesterov: True


minimization_steps: 1

test_action:
  batch_size: 16

test_privacy:
  batch_size: 16

pretrained_action: pretrained/ntu_ShiftGCN_joint_xrep_v2.pt
pretrained_privacy: pretrained/ntu_ShiftGCN_id_xrep_v2.pt
pretrained_privacy_test: pretrained/ntu_ShiftGCN_id_xrep_v2.pt

alpha: 0.3 # privacy loss
beta: 2 # recon loss

wandb: "project_name"
entity: "user"

dataset: "ntu60"